### ISSUE TITLE
Getting the Emergency Response service responding in AWS

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/hackoregon-aws-infrastructure#1]
Project has a successful deploy as per travis build:

However integration endpoint still showing default:

http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/emergency/

Looking through repo wondering if the "path" in this snippet from master.yaml:

    EmerreponseService:
	        Type: AWS::CloudFormation::Stack
	        Properties:
	            TemplateURL: https://s3-us-west-2.amazonaws.com/hacko-infrastructure-cfn/services/emergency-service/service.yaml
	            Parameters:
	                VPC: !GetAtt VPC.Outputs.VPC
	                Cluster: !GetAtt ECS.Outputs.Cluster
	                DesiredCount: 2
	                Listener: !GetAtt ALB.Outputs.Listener
	                ConfigBucket: hacko-emerresponse-config
	                DeployTarget: integration
	                ProjSettingsDir: emerresponseAPI
	                Path: /emergency*

The join in this sinppet ie: "emerresponse":

   EmerresponeServiceUrl:
	        Description: The URL endpoint for the homeless service
	        Value: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "emerresponse" ]]

**Comment by MikeTheCanuck** [comment]
I *think* it's unlikely that the `Path: /emergency*` statement at line 113 of `master.yaml` is the cause of the problem.

Budget service is running and its associated statement at line 85 is `Path: /budget*`.

That said, my suspicions turn to 
- the PROJ_SETTINGS_DIR at line 112 (is "emerresponseAPI" accurate?  It [looks like it](https://github.com/hackoregon/emergency-response-backend/tree/master/emerresponseAPI) but I am not 100% sure if this depends merely on filesystem path or if there's some logical Django object that is also a dependency) 
- the contents of the `service.yaml` for emergency-service - I compared it to the budget-service file and only saw two things of note: (1) ContainerName on line 50 = "emergency-service" and while this is likely just a logical name referenced only within the CF infrastructure, if there's any configuration in the emergency response code that has to match this name, there's plenty of room for naming issues considering all the ways this has been spelled/misspelled/named arbitrarily (seemingly); (2) in the TaskDefinition:Image on line 61, the emergency image is tagged `:latest` whereas budget lacks that tag (which I don't **think** matters but notable all the same)

**Comment by MikeTheCanuck** [comment]
The only other thing that I've noticed that's notable is the fact that when I look at the ECS set of services, sometimes I see 4 tasks running (where 2 are Desired), and other times I see only two:
![image](https://cloud.githubusercontent.com/assets/6953053/24325105/ad835616-114f-11e7-8dd3-83b9668e4af4.png)

When I see two, they're just the `emergency-service:3` Task Definitions.

When I look at the Events tab, it appears that a pair of the Tasks are constantly cycling, never being deemed "healthy" and being killed and regenerated over and over.

There is a continuous stream of messages, all in this repeating pattern:

```
service hacko-integration-EmerreponseService-1LC4181KR6KN5-Service-1WR6VWC6KKIEP has started 2 tasks: task e89237d4-be9d-4abc-9ec9-f5f1b802775a task 8d6a2013-b866-4f84-81a4-a4fd9265af14.

service hacko-integration-EmerreponseService-1LC4181KR6KN5-Service-1WR6VWC6KKIEP registered 2 targets in target-group hacko-Targe-1V7HIUSN1UML6

service hacko-integration-EmerreponseService-1LC4181KR6KN5-Service-1WR6VWC6KKIEP (instance i-04e4ff1f307addd28) (port 36643) is unhealthy in target-group hacko-Targe-1V7HIUSN1UML6 due to (reason Health checks failed)

service hacko-integration-EmerreponseService-1LC4181KR6KN5-Service-1WR6VWC6KKIEP (instance i-04e4ff1f307addd28) (port 36644) is unhealthy in target-group hacko-Targe-1V7HIUSN1UML6 due to (reason Health checks failed)

service hacko-integration-EmerreponseService-1LC4181KR6KN5-Service-1WR6VWC6KKIEP deregistered 2 targets in target-group hacko-Targe-1V7HIUSN1UML6

service hacko-integration-EmerreponseService-1LC4181KR6KN5-Service-1WR6VWC6KKIEP has stopped 2 running tasks: task 8d6a2013-b866-4f84-81a4-a4fd9265af14 task e89237d4-be9d-4abc-9ec9-f5f1b802775a.

service hacko-integration-EmerreponseService-1LC4181KR6KN5-Service-1WR6VWC6KKIEP deregistered 2 targets in target-group hacko-Targe-1V7HIUSN1UML6
```

Next question is: what **Health Check** is being performed, and why is it deemed "failed"?

**Comment by MikeTheCanuck** [comment]
Information to note:

![image](https://cloud.githubusercontent.com/assets/6953053/24325202/ec024374-1150-11e7-9c1e-420f021e5709.png)

I don't believe this is the cause of the unhealthy task, because there is a long period in the past few hours where the memory footprint is well below 100%.  However, this is another piece of information to help us construct a robust service in the future.

**Comment by MikeTheCanuck** [comment]
I pursued a theory just now that didn't give me the answer I was "hoping" for:

## Theory

The currently-configured Emergency Response backend container requires more memory even at startup than the 100 MiB that is allocated by the [service.yml TaskDefinition](https://github.com/hackoregon/hackoregon-aws-infrastructure/blob/master/services/emergency-service/service.yaml).

According to the [CF docs](https://docs.docker.com/compose/compose-file/compose-file-v2/#cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-memswappiness-oomscoreadj-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir), "The number of MiB of memory to reserve for the container. If your container attempts to exceed the allocated memory, the container is terminated."  This isn't exactly the behaviour I think we're seeing - I think the container is running but not giving Health Check the response it's expecting - but it's worth pursuing in case the app is getting into some sort of "unstable" state with not-quite-enough memory.

## Test Approach
- added the following instruction to `local-docker-compose.yml`: `mem_limit: 109051904` (which if my math is correct, is approximately equal to 100 MiB) like so (note: the docs don't make it all that clear if I've specified this correctly):

```
version: '2'
services:
  emergency-service:
    environment:
    - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
    - DEPLOY_TARGET=${DEPLOY_TARGET}
    - CONFIG_BUCKET=${CONFIG_BUCKET}
    build: .
    image: "${DOCKER_IMAGE}"
    command: ./code/bin/docker-entrypoint.sh
    mem_limit: 109051904
    volumes:
      - .:/code
    ports:
      - "8000:8000"
```
- ran `bin/start-proj.sh -l`
- browsed to the http://localhost:8000/emergency page and tested a few of the endpoints

**Expected result**: the app wouldn't even respond, or wouldn't respond quickly, or wouldn't continue to respond after a few requests

**Actual result**: app seems to be responding quickly and consistently, at least to a single GET request on two separate endpoints.

## Next steps
- double-check this is configured correctly in the **docker compose** file
- try reducing the memory allocation further until it finally gives up (to confirm it's taking effect, and to get a feel for what is the lower bound)

**Comment by MikeTheCanuck** [comment]
My top three theories:
1. Naming/spelling of the various bits don't entirely match - I've exhausted the problems that I created and fixed, but there's probably more subtle ones to map.
2. The gunicorn parameters you've set in `docker-entrypoint.sh` (timeout, workers) might be interfering somehow (those aren't specified in budget)
3. The `urlpatterns` in `urls.py` don't have the right namespace??

**Comment by MikeTheCanuck** [comment]
Health check is based on this section of the `service.yaml`:

```
    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            VpcId: !Ref VPC
            Port: 80
            Protocol: HTTP
            Matcher:
                HttpCode: 200-299
            HealthCheckIntervalSeconds: 40
            HealthCheckPath: /emergency/
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 30
            HealthyThresholdCount: 2
```

There's nothing subtle here - if it receives a 2** response to the HTTP request for /emergency/, then it's deemed "healthy".

I don't believe this is an avenue worth pursuing.

**Comment by MikeTheCanuck** [comment]
**Theory**: Django wasn't allowing requests from the ALB and that's why it was failing the Health check.

**Test**: In (this commit](https://github.com/hackoregon/emergency-response-backend/commit/0c8f4f1c4b143fd4da5512b86c32696805dff2c5) I switched ALLOWED_HOSTS to `project_config.ALLOWED_HOSTS` to enable the app to pull in the address we've added for the ALB instance (load balancer).

**Result**: Unfortunately that didn't entirely help - [Travis build #64](https://travis-ci.org/hackoregon/emergency-response-backend/builds/215105696) still couldn't get the deploy running within the timeout.

**Comment by MikeTheCanuck** [comment]
Couple of ideas for us to pursue when we get a chance:
1. @BrianHGrant: Is the SECRET_KEY for Django a special value, or does any string do (and just we happen to be using long, randomly-generated strings because "that's more secure")?
2. Mike: Expand the range of `HttpCode` responses accepted by the Health Check configuration in `service.yaml`.  Not that we will consider "bad" responses healthy, but to determine whether the ALB is even getting *any* response (i.e. is the app running?).

**Comment by BrianHGrant** [comment]
Hey man, I think the SECRET_KEY could really be anything. 

I am attempting to create a vary stripped down version, starting with the basic backend repo and adding in just enough for a single endpoint. Let's see how this goes. If it works, I can then follow a build-test-deploy model to rebuild the API fairly quickly.

**Comment by pdxdiver** [comment]
This has been fixed.  ALB was marking target unhealthy, since the first startup looks like it can take longer than the timeout.  Increased retries.
